c = ["Hyderabad","Chennai",
    "Kolkata", "Pune", "Ahmedabad",
    "Surat", "Rajkot", "Vadodara", "Morbi", "Bhavnagar",
    "Ludhiana", "Jalandhar", "Amritsar",
    "Panipat", "Sonipat", "Faridabad", "Gurgaon",
    "Coimbatore", "Tiruppur", "Erode",
    "Salem", "Madurai",
    "Indore", "Bhopal",
    "Kanpur", "Agra", "Meerut",
    "Jaipur", "Udaipur", "Kota",
    "Bhiwandi", "Thane", "Navi Mumbai",
    "Vapi", "Valsad", "Silvassa",
    "Daman", "Dadra Nagar Haveli",
    "Noida", "Greater Noida", "Ghaziabad",
    "Howrah", "Durgapur",
    "Asansol",
    "Nagpur", "Aurangabad", "Nashik",
    "Kolhapur", "Sangli",
    "Belgaum", "Hubli", "Dharwad",
    "Mysore", "Mangalore",
    "Vijayawada", "Guntur",
    "Warangal",
    "Kochi", "Thrissur", "Kozhikode",
    "Trivandrum",
    "Bhubaneswar", "Cuttack",
    "Raipur", "Bilaspur",
    "Ranchi", "Jamshedpur",
    "Patna",
    "Muzaffarpur",
    "Varanasi", "Prayagraj",
    "Bareilly", "Moradabad",
    "Aligarh",
    "Dehradun", "Haridwar",
    "Roorkee",
    "Saharanpur",
    "Jodhpur", "Bikaner",
    "Ajmer",
    "Guwahati", "Silchar",
    "Imphal",
    "Shillong"
 ]   

x = [
    "wholesaler",
    "supplier",
    "trader",
    "dealer",
    # TEXTILES & APPAREL (High E-commerce Potential)
    "textile manufacturer",
    "garment manufacturer",
    "garment wholesaler",
    "apparel manufacturer",
    "clothing manufacturer",
    "fashion brand",
    "ethnic wear manufacturer",
    "kids wear manufacturer",
    "sportswear manufacturer",
    "t-shirt manufacturer",
    "uniform manufacturer",
    "fabric supplier",
    "yarn manufacturer",

    # HOME & FURNITURE
    "furniture manufacturer",
    "furniture wholesaler",
    "wooden furniture manufacturer",
    "office furniture manufacturer",
    "modular furniture manufacturer",
    "home decor manufacturer",
    "handicraft manufacturer",
    "mattress manufacturer",
    "sofa manufacturer",
    "lighting manufacturer",

    # KITCHEN, HOUSEHOLD & PLASTICS
    "kitchenware manufacturer",
    "cookware manufacturer",
    "plastic product manufacturer",
    "plastic container manufacturer",
    "household plastic manufacturer",
    "storage container manufacturer",
    "water bottle manufacturer",
    "lunch box manufacturer",
    "thermoware manufacturer",

    # PACKAGING (Strong B2B Online Market)
    "packaging manufacturer",
    "corrugated box manufacturer",
    "carton box manufacturer",
    "paper bag manufacturer",
    "flexible packaging manufacturer",
    "label manufacturer",
    "barcode label manufacturer",

    # ELECTRICAL, ELECTRONICS & HARDWARE
    "electrical equipment manufacturer",
    "electrical accessories manufacturer",
    "LED light manufacturer",
    "switchgear manufacturer",
    "cable manufacturer",
    "electronics manufacturer",
    "mobile accessories manufacturer",
    "charger manufacturer",
    "power tools manufacturer",
    "hardware supplier",
    "industrial hardware manufacturer",

    # METAL, TOOLS & ENGINEERING (Product Focused Only)
    "tools manufacturer",
    "hand tools manufacturer",
    "industrial tools supplier",
    "automobile parts manufacturer",
    "auto components manufacturer",
    "machinery manufacturer",
    "industrial equipment supplier",

    # CHEMICALS, COSMETICS & PHARMA
    "cosmetic manufacturer",
    "personal care product manufacturer",
    "skincare product manufacturer",
    "ayurvedic product manufacturer",
    "herbal product manufacturer",
    "pharmaceutical manufacturer",
    "chemical manufacturer",
    "chemical supplier",
    "paint manufacturer",
    "adhesive manufacturer",
    "lubricant manufacturer",

    # FOOD, FMCG & AGRI
    "packaged food manufacturer",
    "snacks manufacturer",
    "namkeen manufacturer",
    "bakery product manufacturer",
    "spices manufacturer",
    "dry fruit wholesaler",
    "organic food manufacturer",
    "dairy product manufacturer",
    "beverage manufacturer",
    "ready to eat food manufacturer",

    # STATIONERY & OFFICE
    "stationery manufacturer",
    "office supplies manufacturer",
    "notebook manufacturer",
    "paper product manufacturer",
    "school supplies manufacturer",

    # CONSTRUCTION & BUILDING MATERIAL
    "building material supplier",
    "sanitaryware manufacturer",
    "tiles manufacturer",
    "ceramic manufacturer",
    "plywood manufacturer",
    "laminate manufacturer",
    "paint supplier"
]