PS D:\Mukul's_data\Business_Scrap\Trademarked_Scrap> py trade_scraper.py
[Process-3] 🔍 MRF authorized dealer Kotputli Behror
[Process-1] 🔍 MRF dealer Ajmer
[Process-2] 🔍 MRF tyre dealer Didwana Kuchaman
[Process-2] 🔁 Chrome crashed, restarting...
[Process-3] 🔁 Chrome crashed, restarting...
[Process-1] 🔁 Chrome crashed, restarting...
[Process-2] 🔁 Chrome crashed, restarting...
[Process-1] 🔁 Chrome crashed, restarting...
[Process-3] 🔁 Chrome crashed, restarting...
[Process-2] 🔁 Chrome crashed, restarting...
[Process-1] 🔁 Chrome crashed, restarting...
